version: "3.9"
services:
  bioc:
    container_name: bioc-3.14
    image: "ghcr.io/nturaga/bioconductor_build_docker:master"
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=bioc
    volumes:
      - ${HOME}/R/bioconductor_docker/3.14:/usr/local/lib/R/host-site-library
